language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: pnH5mijYmLKM3JiPDHuhL7CPeHRr2j6RzgJl1Hlq5regPpJmUpOOrnUJicmrsF5BQKJOi8n6V0aKwJBLwb42Hwxy/qyelJRidur8M9XNXVFUr89qFkilpMT142bGplzKuRVmVlxinS+P7BIiPMS+zoe7EKKu602CrJ2X1C8WFykTvJCYRRa5/F1sLSUTzVxYLEkIVzBwN3lEW+yXadpiGM7jG/jqfxtbCd7+zB2G2tKyqW/wB4qI06Fhf/1tXDYGGF67DHuR6N0hm1o8BaELBZclb5wAQkBOBZLbtOiiO+Rg8C8AxSSL9ENavOF8wKPUT+ctmh0ATtGSwMK4rJqqdwxmjo11+hPmPwwDBtULG09NebY20Zz/zeGrs0E6NuxWM2Jux8lDA+K7WtfvQj7f4a/gj9lFyE99pMIoBWbADbU8xe/lssLVxpnFAEt6ISNNj43Le1YTuUOvgwZWh5Q7knmEcKsdkZ6MENy0J8Lopz3vmASGbOr3ebVkHfk7OqLiV4uDKoyunUxeTQfPD1m+opbGut94x485J/Lb5fhpWqtq0KTrpDyABes82S1vpP48jkf/QWj4/Xy0MFVVhzXYMu/LWhFdgBIgELxgR8AKmr1A7/TbKvZ4jVI0QKt8gQCOLGHmkeTEf+dR0ywrU+MuYSFTt8xmFBMylByUIs5qwR8=
