language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: SoBlptjiLF3lyGspR6G7NnuVlYL9ryJNeQxIXBdplnsb2XIKy5z4ufFyiKacB4R6TPTt9uMg1T5U+WNoa/KH4W734ahhACgOAkmmgI362lyv47JmyiVLbgwzzLbnFBduJ1O39WqYsq0FF2t9GBGIJ9QUDSGetB6OYi6SCSiLw4f/8zvJCB0PugvxJD1hXKSwmuGV71Osr6YFatHf9K8hUJPxjQOywOCJKEqMjksEz2iQ1DMraxONKpysVyX0AiloPWJBnSY/cocP7meWmsKrKuCW2adujDBCoAhrwdYQjGf5exIDG+9mbeFE97ljOFCzMKqN417ddvKphehh4kOPwLW0CeuPEFHHPCrgU728sfjGVr8W0CflyS558oQ1MbTkq3ThjxAcH1NCQVnp5LfZJJDJIDzNcaI37OLCByuNkfIOrxH8rRHw+1ppkz57SDxeLtV2yId72Ee3fjrkABeuM7pLNlWLEW4ow1OusLRA2jJc96d6oiI4y+6EOKG3K1F5gXvEBDGZEtzIa6xIhP259k9RLQ7o/+5yxfxAyTpXq8oL/PajoZRfxh6N4wIBDvq/uVaj2jntmg0p70m8i/FHtqurVxUbnE8PLZtu4jFDwimlfp7pDRzZC4yP3s7qJYW7tj+V93AAWQnvz9QWOlVPmFSgvnw0yKDkvmL2/PBPQAA=
  app: ribbon-guy